/* Generated By:JavaCC: Do not edit this line. EngineConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EngineConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 3;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int DIGITS = 7;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int LETTER = 9;
  /** RegularExpression Id. */
  int COMMENT = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<WHITESPACE>",
    "<EOL>",
    "\"+\"",
    "<NUMBER>",
    "<DIGITS>",
    "<STRING>",
    "<LETTER>",
    "\"\\\\\"",
  };

}
